### ISSUE TITLE
.tsv file not generated when using a list as input to `animint()`

### ISSUE THREAD

**Issue by Faye-yufan** [animint/animint2#102]
**Description:**

When using the **`animint()`** function with internal data, I observed that there are no .tsv data files generated in the specified/temp output directory.
*By 'internal data', I mean the datasets pre-loaded in base package and animint2 package.

**Observations:**

1. For the **`animint()`** function:
    - No .tsv data files are generated in the output directory, either in temporary directory or specific directory, when using internal datasets (like **`mtcars`** in the example).
    
    ```r
    library(animint2)
    viz.point <- list(
    pointtwo = ggplot() + geom_point(
    data = mtcars,
    colour="red",
    colour_off="transparent",
    size = 10,
    aes(x=wt, y=mpg,
    fill = disp),
    clickSelects = "gear")+
    ggtitle("colour=\"red\", colour_off=\"transparent\" "))
    
    # both of the below are not working
    animint(viz.point) # the function would generate a temporary directory
    animint(viz.point, out.dir = "/your/dir") # with a specified directory
    ```
    
    - In contrast, external data behaves as expected. An example can be found **[here](https://github.com/Faye-yufan/gsoc-23-tests/blob/main/medium-RoslingBubbles.R)**, where I used the data from `wbstats` package and the output utilizes a temporary directory and serves the output with `servr`.
2. Now if you try the **`animint2dir()`** function with the same viz list above, it seems to compile and render successfully without any issues.

```r
animint2dir(viz.point, out.dir = "/your/dir")
```

**Comment by ampurr** [comment]
Oo, interesting. I tested it for myself. For some reason, it renders a `.tsv` file on my end. Here's the code I used:

``` r
# Everyone's favorite package
library(animint2)

# So the implicit clickSelects on 
# legends will activate
mtcars$gear <- as.character(mtcars$gear)

# cars make vroom vroom sounds
# unless they're electric 🚗
vroom <- mtcars |>
  ggplot() +
  geom_point() +
  aes(x = wt, y = mpg,
      group = gear, color = gear)

# This generates both the animint
# and the .tsv file
animint(vroom)
```

**Comment by Faye-yufan** [comment]
Oh I see the mix-up now, `animint()` is looking for ggplot objects and `animint2dir()` wants a list. My bad! Maybe we should give users a heads up about the input types if no .tsv files were generated?

**Comment by tdhock** [comment]
yes `animint(...)` arguments should be ggplot objects and options (as documented), this was designed as a substitute for `structure(list(...), class="animint")`.
yes good idea to add an error message in this case.

**Comment by Faye-yufan** [comment]
Oops, my bad for missing that in the docs. For reference:

For animint(): [here](https://github.com/animint/animint2/blob/f99ea2cb4e011f80026e1d6fbdf32f2fa41eaf2b/R/z_print.R#L31)
And for animint2dir(): [here](https://github.com/animint/animint2/blob/f99ea2cb4e011f80026e1d6fbdf32f2fa41eaf2b/R/z_animint.R#L228)

**Comment by ampurr** [comment]
> Cars make vroom vroom sounds 
> unless they're electric 🚗

Apparently electric cars also make vroom vroom sounds. It's like a law thing so hearing people can hear the cars and not get hit. Anyway, just wanted to correct this factual inaccuracy. Thank you. :>
