### ISSUE TITLE
animint2netlify

### ISSUE THREAD

**Issue by tdhock** [animint/animint2#108]
Netlify drop allows publishing static sites https://app.netlify.com/drop/
can we use this with an API?
If so we could make a function animint2netlify() similar to old animint2gist()
@Faye-yufan did you know about that?

**Comment by tdhock** [comment]
is there a time limit after which the site will be taken down?
is there a size limit for each file?
limit to the number of files?

**Comment by Faye-yufan** [comment]
Thanks for sharing this! I did not know that before, it's a great resource. I will look into it.

**Comment by tdhock** [comment]
https://docs.netlify.com/api/get-started/ says
You can make up to 500 requests per minute.
That page also has instructions for using the API, but is there an R package which already implements the netlify API?

**Comment by Faye-yufan** [comment]
From what I've looked into, I haven't found any packages specifically designed for the Netlify API.
https://github.com/netlify/NetlifyDS this one has been archived, but I don't see any API in the package.

**Comment by tdhock** [comment]
on second thought I think we should encourage use of animint2pages, so that making galleries is easy with the new update_gallery function. So no need to make an animint2netlify function I think.
I will keep this open as a reminder to mention netlify drop on https://rcdata.nau.edu/genomic-ml/animint2-manual/Ch05-sharing.html
