### ISSUE TITLE
No Plot visible on web page 

### ISSUE THREAD

**Issue by Tushar98644** [animint/animint2#118]
I was following the [The animint2 manual](https://rcdata.nau.edu/genomic-ml/animint2-manual/Ch02-ggplot2.html) and was correctly able to use the ggplot2 package. However when i try to use the animint2 package functions , i end with an empty webpage (shown below) . I have followed the [wiki FAQ](https://github.com/tdhock/animint2/wiki/FAQ#web-browser-on-local-indexhtml-file-is-blank) but this still doesn't seem to work. 
```
> animint(scatter)
Saving animint in temporary directory; specify output directory using animint(out.dir="path/to/directory")
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /private/var/folders/n0/g4tc383d3pz_wgjgb2511vy80000gn/T/RtmpSwpzPI/file6b6c6c17e98 at http://127.0.0.1:4321
```

screenshot : 

<img width="1440" alt="Screenshot 2024-03-05 at 10 53 17 PM" src="https://github.com/animint/animint2/assets/107763774/366b397b-195d-47af-9a81-1c90bc3d0253">

**Comment by tdhock** [comment]
you should do what it says in the message: `animint(out.dir="path/to/directory")` then look in that directory to see if the files are there, and then look at index.html in the web browser. When you figure it out, please post a solution here, and edit the wiki to clarify how to fix this, in order to help others in the future.

**Comment by Tushar98644** [comment]
> you should do what it says in the message: `animint(out.dir="path/to/directory")` then look in that directory to see if the files are there, and then look at index.html in the web browser. When you figure it out, please post a solution here, and edit the wiki to clarify how to fix this, in order to help others in the future.

<img width="1440" alt="Screenshot 2024-03-06 at 11 25 07 AM" src="https://github.com/animint/animint2/assets/107763774/311611d0-4436-4c9f-88c3-1e2c09bab6ac">

I generated the files in an output directory and tried running the index.html file through live server, getting the same issue

<img width="821" alt="Screenshot 2024-03-06 at 11 27 20 AM" src="https://github.com/animint/animint2/assets/107763774/8eef6457-9d19-483d-b49b-916ff57ab6c9">

**Comment by tdhock** [comment]
which web browser are you using? what version number? did you look at its Inspect panel / javascript error console, to see what the problem is? Did you try any other web browsers? (if not, you should)

**Comment by tdhock** [comment]
did you try editing your web browser's preferences to allow execution of local javascript code? (if not, you should)

**Comment by Tushar98644** [comment]
> which web browser are you using? what version number? did you look at its Inspect panel / javascript error console, to see what the problem is? Did you try any other web browsers? (if not, you should)

yup , i tried the following browsers : 
 1) Chrome - enable javascript execution
 2) Brave - shield off and javascript enabled 
 3 ) safari - javascript enabled

**Comment by Tushar98644** [comment]
> which web browser are you using? what version number? did you look at its Inspect panel / javascript error console, to see what the problem is? Did you try any other web browsers? (if not, you should)

The chrome browser console is empty but the js files are loading correctly

<img width="1440" alt="Screenshot 2024-03-06 at 9 18 55 PM" src="https://github.com/animint/animint2/assets/107763774/fa72df08-04c4-468a-94bd-307d8245a16a">

**Comment by Tushar98644** [comment]
> > which web browser are you using? what version number? did you look at its Inspect panel / javascript error console, to see what the problem is? Did you try any other web browsers? (if not, you should)
> 
> yup , i tried the following browsers :
> 
> 1. Chrome - enabled javascript execution
> 2. Brave - shield off and javascript enabled
> 3. safari - javascript enabled

**Comment by tdhock** [comment]
I would suggest  trying firefox, instructions here https://github.com/animint/animint2/wiki/FAQ#web-browser-on-local-indexhtml-file-is-blank

**Comment by Tushar98644** [comment]
> I would suggest trying firefox, instructions here https://github.com/animint/animint2/wiki/FAQ#web-browser-on-local-indexhtml-file-is-blank

I installed firefox and set `security.fileuri.strict_origin_policy` to `false` , somehow the plot is now getting displayed on all the browsers (not sure why )

<img width="1440" alt="Screenshot 2024-03-06 at 9 50 24 PM" src="https://github.com/animint/animint2/assets/107763774/084a3c21-b91a-42fc-805a-765c828c6529">

**Comment by Tushar98644** [comment]
> great. please edit the wiki if there is anything you did to fix, which is different from what is already written there.

sure. I am interested in working on the [Animated interactive ggplots](https://github.com/rstats-gsoc/gsoc2024/wiki/Animated-interactive-ggplots) idea for gsoc and will soon complete the tasks under that .  Sir , is there any slack or discord channel where we can continue discussion on the same

**Comment by tdhock** [comment]
great, thanks for your interest in GSOC!
there is no slack nor discord, so please use github issues.

**Comment by Tushar98644** [comment]
> great, thanks for your interest in GSOC! there is no slack nor discord, so please use github issues.

sure sir , so i assume i can open new issues when i have to discuss something ? Also can you link me to some documentation which can help me in understanding the codebase better . Thanks

**Comment by Tushar98644** [comment]
Also any beginner-friendly issues I can currently work upon?

**Comment by tdhock** [comment]
hi thanks for sharing your data viz.
that is a good start.
please add a linked time series plot where you can click to select the year.

**Comment by Tushar98644** [comment]
> hi thanks for sharing your data viz. that is a good start. please add a linked time series plot where you can click to select the year.

Updated the [time series plots](https://tushar98644.github.io/Animint2_Tests/language_statistics/index.html) and also completed the [medium assignment](https://tushar98644.github.io/Animint2_Tests/monte-carlo-integration/index.html)
