### ISSUE TITLE
Collaboration plan for GSOC'24

### ISSUE THREAD

**Issue by siddhesh195** [animint/animint2#129]
Siddhesh Deodhar and Nhi Truong has the following collaboration plan for GSoC 2024:

1) Porting the existing ~50 visualization gallery from the NAU rcdata server to a new GitHub Pages gallery
    Nhi: Setup the gallery and port first 25 visualizations
    Siddhesh: Port next set of visualizations (26- ~50) 
        
2) Replacing phantomjs with Chrome as the headless browser for testing by modifying test code, analyzing and fixing issues causing failed tests, and updating the GitHub Actions workflow. 
    Siddhesh: Establish chromote as headless browser and fix failing tests (This task is already in progress)
    Nhi: Update GitHub Actions workflow after Siddhesh finishes his task    

3) Enhancing the animint2pages function to use to automatically capture screenshots of generated pages and copy them to the appropriate folder. 
    Siddhesh: Study chromote and its suitability to capture screenshots
    Nhi: Study webshot and its suitability to capture screenshots
    Both Siddhesh/Nhi:  Add support of the selected tool, add tests, write documentation
     
4) Extending the package to support more interactive visualization types and potentially implement flexible ggplot layouts in HTML tables.
     Siddhesh: Add basic support to implement ggplot layouts in HTML tables
     Nhi: Extend Siddhesh's feature and support more advanced features such as rowspan, columnspan, any table customizations

**Comment by siddhesh195** [comment]
@nhintruong, please review this proposal when you get a chance

**Comment by Faye-yufan** [comment]
Hey @siddhesh195 @nhintruong, do you know how to use the Git command line to push and commit changes?
I've scheduled a meeting on 06/13. Please join if you have any questions. I have emailed the invite to both of you about the meeting details.

**Comment by siddhesh195** [comment]
> Hey @siddhesh195 @nhintruong, do you know how to use the Git command line to push and commit changes? I've scheduled a meeting on 06/13. Please join if you have any questions. I have emailed the invite to both of you about the meeting details.

I have not used Git command line yet. I have only used Git client for Mac. yes, I will be there for the meeting. thanks

**Comment by Faye-yufan** [comment]
Hi @siddhesh195 , I saw your commit message on this commit https://github.com/animint/animint2/pull/131/commits/73d540f407f39f1f2245f7bbaac1198c434d048a, well done!!

Here are some additional resources for future reference: [Conventional Commit Messages](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13#conventional-commit-messages-), [How to Write Good Commit Messages: A Practical Git Guide](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/)

**Comment by Faye-yufan** [comment]
@siddhesh195 @nhintruong, as discussed in today's meeting related to blog. Here is the approach I did for my GSoC blog:
1. I forked from this repo [beautiful-jekyll](https://github.com/daattali/beautiful-jekyll), which serves as a template.
2. Follow their instruction to set up the blog [The easy way (recommended!)](https://github.com/daattali/beautiful-jekyll?tab=readme-ov-file#the-easy-way-recommended)

Once everything is set up, updating the blog using Markdown will be much easier.

**Comment by tdhock** [comment]
hi @siddhesh195 I see small commits in some branches but otherwise I have no idea what you are working on, and how I can help. please start writing every day what you have been working on, either in this issue or start a new one, make sure to push any commits to github, and create issues to ask for help with specific questions. example of what I expect https://github.com/Nj221102/data.table-gSoc-24-project/issues/1

**Comment by siddhesh195** [comment]
> hi @siddhesh195 I see small commits in some branches but otherwise I have no idea what you are working on, and how I can help. please start writing every day what you have been working on, either in this issue or start a new one, make sure to push any commits to github, and create issues to ask for help with specific questions. example of what I expect [Nj221102/data.table-gSoc-24-project#1](https://github.com/Nj221102/data.table-gSoc-24-project/issues/1)

@tdhock @Faye-yufan I am currently working on implementing the screenshot functionality (PR #131) using chromote screenshot API. I was able to locally save the screenshot. I am now working on adding the code to send it to Github pages, writing a test and working on draft of the documentation. I expect to complete all of that by Friday. But I am facing a small issue. If I run the compiler-ghpages test it passes for the first time. But if I run it again immediately I get an error. Here is the screenshot of the error :
<img width="747" alt="Screenshot 2024-06-19 at 6 41 10 PM" src="https://github.com/animint/animint2/assets/153800103/77ae6879-d952-4ec4-b6bb-2c359037cb71">

**Comment by siddhesh195** [comment]
@tdhock @Faye-yufan I am facing an issue while I am working on #131 . If I run the compiler-ghpages test it passes for the first time. But if I run it again immediately I get an error. Here is the screenshot of the error :
<img width="747" alt="Screenshot 2024-06-19 at 6 41 10 PM" src="https://github.com/animint/animint2/assets/153800103/77ae6879-d952-4ec4-b6bb-2c359037cb71">

**Comment by siddhesh195** [comment]
> hi @siddhesh195 I see small commits in some branches but otherwise I have no idea what you are working on, and how I can help. please start writing every day what you have been working on, either in this issue or start a new one, make sure to push any commits to github, and create issues to ask for help with specific questions. example of what I expect [Nj221102/data.table-gSoc-24-project#1](https://github.com/Nj221102/data.table-gSoc-24-project/issues/1)

@tdhock I have created a new issue (#133 ) to give my daily status updates

**Comment by Faye-yufan** [comment]
Just some notes from today's meeting:

- Hi @nhintruong , could you please add the visualization links to the gallery PR https://github.com/animint/gallery/pull/4, so everyong can preview them easily?
- For your next gallery visualization porting, please create separate PRs so we can easily track each one.
- Hi @siddhesh195 , could you please create an issue for the animint2page test case?
- For the chromote image capture, could you crop the white space out? The [magick](https://docs.ropensci.org/magick/articles/intro.html) package might be helpful for this.
- I have created a new google meeting invite for next Tuesday Jun 25, to debug Chromote on Linux OS. The same link as today's meeting, hope the link will still work 🤞 

To better help you, let's keep the conversation small, please update us daily on your progress issues https://github.com/animint/animint2/issues/133, https://github.com/animint/animint2/issues/128. Feel free to ask any questions!

**Comment by siddhesh195** [comment]
> Just some notes from today's meeting:
> 
> * Hi @nhintruong , could you please add the visualization links to the gallery PR [Porting visualization gallery gallery#4](https://github.com/animint/gallery/pull/4), so everyong can preview them easily?
> * For your next gallery visualization porting, please create separate PRs so we can easily track each one.
> * Hi @siddhesh195 , could you please create an issue for the animint2page test case?
> * For the chromote image capture, could you crop the white space out? The [magick](https://docs.ropensci.org/magick/articles/intro.html) package might be helpful for this.
> * I have created a new google meeting invite for next Tuesday Jun 25, to debug Chromote on Linux OS. The same link as today's meeting, hope the link will still work 🤞
> 
> To better help you, let's keep the conversation small, please update us daily on your progress issues #133, #128. Feel free to ask any questions!

@Faye-yufan I have created issue (#135 ) for error in test case compiler-ghpages. thank you

**Comment by siddhesh195** [comment]
@nhintruong: Can you please review this updated collaboration plan and comment if it is okay ? I have nearly finished tasks 2,3 but we can still split parts of tasks 1,4
@tdhock @Faye-yufan Please let me know if the updated collaboration plan looks okay

Updated collaboration plan for GSoC 2024:

1. **Porting the existing ~50 visualization gallery from the NAU rcdata server to a new GitHub Pages gallery**

Nhi: Setup the gallery and port first 25 visualizations
Siddhesh: Port next set of visualizations (26- ~50)

2. **Replacing phantomjs with Chrome as the headless browser for testing by modifying test code, analyzing and fixing issues causing failed tests, and updating the GitHub Actions workflow.**
Siddhesh: Siddhesh has completed this task

3. **Enhancing the animint2pages function to use to automatically capture screenshots of generated pages and copy them to the appropriate folder.**
Siddhesh: Completed of most this task using chromote, added a test (Most of this task has been done and currently fixing blank screenshot error observed for a plot)
Nhi: Improve the captured screenshot by trimming white shapes around plots (The screenshot() currently captures the entire browser area)

4. **Extending the package to support more interactive visualization types and potentially implement flexible ggplot layouts in HTML tables.**
Siddhesh: Add basic support to implement ggplot layouts in HTML tables
Nhi: Extend Siddhesh's feature and support more advanced features such as rowspan, columnspan, any table customizations.

**Comment by tdhock** [comment]
it is ok but I suspect Nhi may need your help, plan on working together for the rowspan etc

**Comment by siddhesh195** [comment]
> @nhintruong: Can you please review this updated collaboration plan and comment if it is okay ? I have nearly finished tasks 2,3 but we can still split parts of tasks 1,4 @tdhock @Faye-yufan Please let me know if the updated collaboration plan looks okay
> 
> Updated collaboration plan for GSoC 2024:
> 
> 1. **Porting the existing ~50 visualization gallery from the NAU rcdata server to a new GitHub Pages gallery**
> 
> Nhi: Setup the gallery and port first 25 visualizations Siddhesh: Port next set of visualizations (26- ~50)
> 
> 2. **Replacing phantomjs with Chrome as the headless browser for testing by modifying test code, analyzing and fixing issues causing failed tests, and updating the GitHub Actions workflow.**
>    Siddhesh: Siddhesh has completed this task
> 3. **Enhancing the animint2pages function to use to automatically capture screenshots of generated pages and copy them to the appropriate folder.**
>    Siddhesh: Completed of most this task using chromote, added a test (Most of this task has been done and currently fixing blank screenshot error observed for a plot)
>    Nhi: Improve the captured screenshot by trimming white shapes around plots (The screenshot() currently captures the entire browser area)
> 4. **Extending the package to support more interactive visualization types and potentially implement flexible ggplot layouts in HTML tables.**
>    Siddhesh: Add basic support to implement ggplot layouts in HTML tables
>    Nhi: Extend Siddhesh's feature and support more advanced features such as rowspan, columnspan, any table customizations.

@tdhock @Faye-yufan @nhintruong  In a meeting with Nhi few days ago I asked her if she can complete the entire gallery task on her own. She told me she can. But I told her I can still share the work of that task at any point in the future if she wants. Right now I am working on the screenshot task(#131) and will start the html table layout task as soon as I am done with it

**Comment by Faye-yufan** [comment]
@siddhesh195 and I had a meeting today (07/11), we discussed how to test in both R compiler side and JS renderer side. 

Hi @nhintruong , could you please update your status with Siddhesh as well? This will help you two avoid duplicating work. Thanks!

**Comment by Faye-yufan** [comment]
@siddhesh195 and I had a meeting on 07/18, discussed about the helper function in tests, see [this](https://github.com/animint/animint2/pull/126#discussion_r1682965897). Also Siddhesh explained how a persistent server works for capturing screenshots in animint2pages.

**Comment by nhintruong** [comment]
@tdhock @Faye-yufan The link for the 59th data visualization in the gallery (https://rcdata.nau.edu/genomic-ml/animint-gallery/) points back to itself rather than to the source code. Could you please recheck it and provide me with the correct source code link for this visualization? Thank you very much for your guidance

![image](https://github.com/user-attachments/assets/281bcb0d-d4b4-4758-99ba-7c1545a8948a)

**Comment by Faye-yufan** [comment]
> @tdhock @Faye-yufan The link for the 59th data visualization in the gallery (https://rcdata.nau.edu/genomic-ml/animint-gallery/) points back to itself rather than to the source code. Could you please recheck it and provide me with the correct source code link for this visualization? Thank you very much for your guidance
> 


This is a valid issue, @nhintruong please create an issue in https://github.com/animint/gallery/issues

**Comment by Faye-yufan** [comment]
Hi @siddhesh195 @nhintruong , please refer to this [blog](https://support.posit.co/hc/en-us/articles/205612627-Debugging-with-the-RStudio-IDE) about the debugging process in R studio. It can help you go through and understand animint2 internal core functions.

Siddhesh -  in your case, use `debug(animint2::theme_animint)` and run your test case to trigger this function in debug mode, and then use the RStudio IDE debug tool to go thru it to see how width/height works. Hope this is helpful for the development of `row` and `col`.

**Comment by tdhock** [comment]
also instead of debug(fun) you can just add browser() anywhere in that fun.
