### ISSUE TITLE
compiler-ghpages test failing when executed again in succession in the same RStudio session.

### ISSUE THREAD

**Issue by siddhesh195** [animint/animint2#135]
I am using RStudio Version 2024.04.0+735 (2024.04.0+735) on Arm Mac OS 14.4.1. 

The compiler-ghpages test case fails the second time when executed again in the same RStudio session. If RStudio is restarted it passes again.

the error messages are:

> tests_run(filter="ghpages")
[1] "GitHub Pages"
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 3 ]

══ Failed tests ═════════════════════════════════════════════════════════════════════════════════════
── Error (test-compiler-ghpages.R:26:3): animint2pages() returns owner/repo string ──
Error in `value[[3L]](cond)`: A GitHub token is required to create and push to a new repository. 
To create a GitHub token, follow these steps:
1. Go to https://github.com/settings/tokens/new?scopes=repo&description=animint2pages
2. Confirm your password if prompted.
3. Ensure that the 'repo' scope is checked.
4. Click 'Generate token' at the bottom of the page.
5. Copy the generated token.
After creating the token, you can set it up in your R environment by running: 
Sys.setenv(GITHUB_PAT="yourGithubPAT") 
gert::git_config_global_set("user.name", "yourUserName") 
gert::git_config_global_set("user.email", "yourEmail") 

Backtrace:
    ▆
 1. └─animint2::animint2pages(viz, github_repo = "animint2pages_test_repo") at test-compiler-ghpages.R:26:3
 2.   └─base::tryCatch(...)
 3.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         └─value[[3L]](cond)

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 3 ]

**Comment by tdhock** [comment]
instead of screenshot/image please paste text (easier to search)

**Comment by siddhesh195** [comment]
> instead of screenshot/image please paste text (easier to search)

@tdhock I have replaced the screenshot with text. thank you

**Comment by tdhock** [comment]
hi @siddhesh195 is this still a problem? if so, please clarify. if not, please close.

**Comment by siddhesh195** [comment]
> hi @siddhesh195 is this still a problem? if so, please clarify. if not, please close.

This is no longer a problem, the test passes on github actions as well as locally as long as GitHub with appropriate permissions exists locally
