### ISSUE TITLE
Hard test(gsoc)-->Error getting while going unittest

### ISSUE THREAD

**Issue by busttech** [animint/animint2#173]
code 
``` 
library(testthat)
library(animint2)

test_that("Animint renderer test works", {
  # Create a simple Animint object
  viz <- animint(
    data = data.frame(x = 1:10, y = rnorm(10)),
    aes(x = x, y = y),
    geom = "point"
  )
  
  # Use animint2HTML to render the visualization to a temporary directory
  temp_dir <- tempdir()
  output <- animint2HTML(viz, out.dir = temp_dir)
  
  # Check if the output HTML file exists
  expect_true(file.exists(file.path(temp_dir, "index.html")), 
              "HTML file was not created.")
  
  # Optionally: Check the content of the HTML file
  html_content <- readLines(file.path(temp_dir, "index.html"))
  expect_true(grepl("d3", html_content[1]), "HTML file does not contain d3.js.")
})
``` 
Its showing error
![Screenshot 2024-12-01 103635](https://github.com/user-attachments/assets/d93d29ec-d388-46e6-888c-34900d8e36ef)
I think problem is that animint2 doesnot have function animint2html and animint is not compatible with my R version can you tell me which version of r require for animint.

**Comment by ampurr** [comment]
Maybe I'm missing something. But I'm a little confused. If animint2 doesn't have an `animint2HTML` function, why are you trying to use it? 😮

**Comment by busttech** [comment]
Because they told to use it

**Comment by ampurr** [comment]
I'm not familiar with what GSOC is saying: Could you point to where the GSOC document says so? You may also want to take a look at the animint2 documentation, especially at the list of functions. I have some confidence that the solution to your coding woes is in there. 😄

Regarding R version... I guess the latest one? Toby could probably tell you more if it's relevant.

**Comment by tdhock** [comment]
did you read this? https://github.com/animint/animint2/wiki/Chromote-testing-documentation

**Comment by busttech** [comment]
Sorry I was not doing this properly Now I am able to do this and i also added the tests and pr link is https://github.com/animint/animint2/pull/175
