### ISSUE TITLE
sign up for saucelabs for testing?

### ISSUE THREAD

**Issue by tdhock** [animint/animint2#41]
hi @lazycipher can you please sign up for a free open source account on https://saucelabs.com/platform which may be useful for headless browser testing?

**Comment by lazycipher** [comment]
Sure thing! It sounds like a good idea!

**Comment by tdhock** [comment]
hi did you sign up? or do you think it is not necessary? (travis + docker is sufficient?)

**Comment by lazycipher** [comment]
I think Travis + Docker is sufficient but I'll give it a try to find if it can make the process more smooth.
