### ISSUE TITLE
Axes and legends improvements

### ISSUE THREAD

**Issue by csaluski** [animint/animint2#62]
I was reading [this article](https://observablehq.com/@vega/a-guide-to-guides-axes-legends-in-vega) about the design of plot axes and legends, specifically in Vega, but the ideas seem universally applicable. It made me wonder how flexible Animint's systems for these currently are, and if it's currently possible to recreate all of the options show in that article, or if further options would have to be implemented before it reaches those capabilities. If there are some that are not currently possible it might be worth opening individual discussions into them and working on making our system as flexible as possible.

**Comment by csaluski** [comment]
One that currently doesn't seem possible and would be very useful for visualizations is the discrete gradient legends. Currently this is possible in [ggplot](https://ggplot2.tidyverse.org/reference/scale_steps.html), however I think that was added after Animint diverged from it.

**Comment by tdhock** [comment]
you are right, the discrete gradient legends are not possible, but there is a work-around, just compute the discretization yourself as a factor variable and use that, which will make a categorical legend that shows basically the same information.
